name: Test Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload-to-gdrive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Create service account file
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Create rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "[drive]" > ~/.config/rclone/rclone.conf
          echo "type = drive" >> ~/.config/rclone/rclone.conf
          echo "scope = drive" >> ~/.config/rclone/rclone.conf
          echo "service_account_file = /tmp/sa.json" >> ~/.config/rclone/rclone.conf
          echo "root_folder_id = 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH" >> ~/.config/rclone/rclone.conf

      - name: Upload file to Google Drive
        run: |
          rclone copy ./spotify.png drive: -P
