name: Test GDrive Service Account

on:
  workflow_dispatch:

jobs:
  test-sa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Save Service Account Key
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Test Rclone with Service Account
        run: |
          rclone about gdrive: --drive-service-account-file /tmp/sa.json
