name: Upload to Drive

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rclone
        run: sudo apt update && sudo apt install -y rclone

      - name: Create Service Account JSON
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Create rclone.conf
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [drive]
          type = drive
          scope = drive
          service_account_file = /tmp/sa.json
          root_folder_id = 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH
          EOF

      - name: Test rclone
        run: rclone about drive:

      - name: Upload file
        run: rclone copy ./spotify.png drive: -P
